name: docs-staging

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  docs-build:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.DOCS_DEPLOY }}
      - name: predocs
        run: |
          npm i
      - name: Push docs branch
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOY_ENV: staging
        run: |
          git config --global user.email "zephyr-sdk-api@listenai.com"
          git config --global user.name "zephyr-sdk-api-docs"
          node deploy.js
      - name: action LSOpenWeb deploy
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "zephyr-sdk-api@listenai.com"
          git config --global user.name "zephyr-sdk-api-docs"
          node action.js